/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        page: 'var(--bg-page)',
        surface: {
          DEFAULT: 'var(--bg-surface)',
          hover: 'var(--bg-surface-hover)',
          subtle: 'var(--bg-surface-subtle)',
        },
        line: {
          DEFAULT: 'var(--border-main)',
          subtle: 'var(--border-subtle)',
        },
        txt: {
          heading: 'var(--text-heading)',
          body: 'var(--text-body)',
          muted: 'var(--text-muted)',
          dim: 'var(--text-dim)',
        },
        admin: {
          bg: {
            dark: 'var(--bg-page)',
            light: 'var(--bg-page)',
          },
          surface: {
            dark: 'var(--bg-surface)',
            darkHover: 'var(--bg-surface-hover)',
            darkSubtle: 'var(--bg-surface-subtle)',
            light: 'var(--bg-surface)',
            lightHover: 'var(--bg-surface-hover)',
          },
          border: {
            dark: 'var(--border-main)',
            darkSubtle: 'var(--border-subtle)',
            light: 'var(--border-main)',
            lightSubtle: 'var(--border-subtle)',
          },
        },
        primary: {
          DEFAULT: '#15803D',
          dark: '#166534',
          light: '#DCFCE7',
          50: '#F0FDF4',
          100: '#DCFCE7',
          200: '#BBF7D0',
          300: '#86EFAC',
          400: '#4ADE80',
          500: '#22C55E',
          600: '#16A34A',
          700: '#15803D',
          800: '#166534',
          900: '#14532D',
        },
        brand: {
          emerald: '#10B981',
          dark: '#064E3B',
          glow: 'rgba(16, 185, 129, 0.15)',
        },
        gold: {
          DEFAULT: '#D4A017',
          light: '#FEF3C7',
          dark: '#A16207',
        },
        status: {
          success: '#16A34A',
          'success-bg': '#DCFCE7',
          warning: '#D97706',
          'warning-bg': '#FEF3C7',
          error: '#DC2626',
          'error-bg': '#FEE2E2',
          info: '#2563EB',
          'info-bg': '#DBEAFE',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        sm: 'var(--admin-radius, 0px)',
        DEFAULT: 'var(--admin-radius, 0px)',
        md: 'var(--admin-radius, 0px)',
        lg: 'var(--admin-radius, 0px)',
        xl: 'var(--admin-radius, 0px)',
        '2xl': 'var(--admin-radius, 0px)',
        '3xl': 'var(--admin-radius, 0px)',
        full: 'var(--admin-radius, 0px)',
        btn: 'var(--admin-radius, 0px)',
        input: 'var(--admin-radius, 0px)',
        card: 'var(--admin-radius, 0px)',
        panel: 'var(--admin-radius, 0px)',
        pill: 'var(--admin-radius, 0px)',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0, 0, 0, 0.08)',
        'card-dark': '0 2px 8px rgba(0, 0, 0, 0.4)',
        glow: '0 0 16px rgba(16, 185, 129, 0.2)',
      },
    },
  },
  plugins: [],
}
